package agent

import (
	"context"
	"fmt"
	"strings"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"github/musuyin/agent-weave/internal/model/repository"
)

// RunSubAgent executes a single subagent turn. Intended to be called in a goroutine.
// It builds the subagent's system prompt (agent.Prompt + loaded skill bodies), calls
// the LLM once (no tools — subagents are text-only), persists the result with the
// agent's ID, and signals the DispatchRegistry on completion.
//
// Invariant D: message IDs are independently generated by persistMessage.
// Invariant C: thread status is updated via a short per-thread transaction.
func (s *Service) RunSubAgent(
	ctx context.Context,
	conversationID string,
	thread repository.Thread,
	instruction string,
	hub *Hub,
	reg *DispatchRegistry,
) {
	agentID := thread.AgentID
	agentName := agentID // fallback; overwritten below

	var output string
	var runErr error

	defer func() {
		status := repository.ThreadStatusDone
		if runErr != nil {
			status = repository.ThreadStatusError
		}
		// Short per-thread transaction (invariant C).
		_ = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			return tx.Model(&repository.Thread{}).
				Where("id = ?", thread.ID).
				Update("status", status).Error
		})
		hub.Push(SSEEvent{Type: EventThreadStatus, Data: ThreadStatusData{
			ThreadID:  thread.ID,
			Status:    string(status),
			AgentName: agentName,
		}})
		reg.Done(conversationID, SubAgentResult{
			AgentName: agentName,
			ThreadID:  thread.ID,
			Output:    output,
			Err:       runErr,
		})
	}()

	// Load agent definition + skills.
	agentDef, err := s.agentSvc.Get(ctx, agentID)
	if err != nil {
		runErr = fmt.Errorf("load agent %s: %w", agentID, err)
		return
	}
	agentName = agentDef.Name

	skills, err := s.agentSvc.ListSkills(ctx, agentID)
	if err != nil {
		runErr = fmt.Errorf("load skills for agent %s: %w", agentID, err)
		return
	}

	// Build system prompt: agent prompt + skill bodies.
	var sb strings.Builder
	sb.WriteString(agentDef.Prompt)
	for _, sk := range skills {
		sb.WriteString("\n\n")
		sb.WriteString(sk.Body)
	}
	systemPrompt := sb.String()

	// Build history and append instruction as a synthetic user turn.
	history, err := s.loadHistory(ctx, conversationID)
	if err != nil {
		runErr = fmt.Errorf("load history: %w", err)
		return
	}
	history = append(history, anthropic.NewUserMessage(
		anthropic.NewTextBlock(instruction),
	))

	// Single LLM turn — no tools for subagents.
	stream := s.aiClient.Messages.NewStreaming(ctx, anthropic.MessageNewParams{
		Model:     anthropic.Model(s.cfg.LLMModel.Anthropic.Model),
		MaxTokens: 8096,
		System:    []anthropic.TextBlockParam{{Text: systemPrompt}},
		Messages:  history,
	})

	blockIDs := map[int64]string{}
	accMsg := anthropic.Message{}

	for stream.Next() {
		event := stream.Current()
		_ = accMsg.Accumulate(event)

		switch ev := event.AsAny().(type) {
		case anthropic.ContentBlockStartEvent:
			bid := uuid.NewString()
			blockIDs[ev.Index] = bid
			blockType := "text"
			if ev.ContentBlock.Type == "tool_use" {
				blockType = "tool_use"
			}
			hub.Push(SSEEvent{Type: EventBlockStart, Data: BlockStartData{
				BlockID: bid, BlockType: blockType, Index: ev.Index,
			}})
		case anthropic.ContentBlockDeltaEvent:
			if delta, ok := ev.Delta.AsAny().(anthropic.TextDelta); ok && delta.Text != "" {
				hub.Push(SSEEvent{Type: EventBlockDelta, Data: BlockDeltaData{
					BlockID: blockIDs[ev.Index], Text: delta.Text, Index: ev.Index,
				}})
			}
		case anthropic.ContentBlockStopEvent:
			hub.Push(SSEEvent{Type: EventBlockStop, Data: BlockStopData{
				BlockID: blockIDs[ev.Index], Index: ev.Index,
			}})
		}
	}

	if err := stream.Err(); err != nil {
		runErr = fmt.Errorf("stream: %w", err)
		return
	}

	// Collect text blocks and persist with this agent's ID.
	var blocks repository.ContentBlocks
	for _, cb := range accMsg.Content {
		if cb.Type == "text" {
			blocks = append(blocks, repository.ContentBlock{Type: "text", Text: cb.Text})
			output += cb.Text
		}
	}
	if len(blocks) > 0 {
		if err := s.persistMessage(ctx, conversationID, "assistant", blocks, &agentID); err != nil {
			runErr = fmt.Errorf("persist subagent message: %w", err)
			return
		}
	}
}
