// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github/musuyin/agent-weave/internal/agent"
	"github/musuyin/agent-weave/internal/config"
	"github/musuyin/agent-weave/internal/db"
	"github/musuyin/agent-weave/internal/handler"
	"github/musuyin/agent-weave/internal/service"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns a ready Gin engine plus a cleanup func.
func InitializeApp(ctx context.Context, log *slog.Logger) (*gin.Engine, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	gormDB, cleanup, err := db.ProvideDB(configConfig, log)
	if err != nil {
		return nil, nil, err
	}
	hubRegistry := agent.NewHubRegistry(log)
	agentService := agent.ProvideAgentService(gormDB, configConfig, hubRegistry, log)
	conversationService := service.NewConversationService(gormDB)
	messageService := service.NewMessageService(gormDB)
	conversationHandler := handler.NewConversationHandler(conversationService)
	messageHandler := handler.NewMessageHandler(messageService, agentService, hubRegistry)
	streamHandler := handler.NewStreamHandler(hubRegistry, messageService)
	engine := handler.ProvideRouter(conversationHandler, messageHandler, streamHandler, log)
	return engine, func() {
		cleanup()
	}, nil
}
