// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github/musuyin/agent-weave/internal/agent"
	"github/musuyin/agent-weave/internal/config"
	"github/musuyin/agent-weave/internal/db"
	"github/musuyin/agent-weave/internal/handler"
	"github/musuyin/agent-weave/internal/hook"
	"github/musuyin/agent-weave/internal/mcp"
	"github/musuyin/agent-weave/internal/service"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns a ready Gin engine plus a cleanup func.
func InitializeApp(ctx context.Context, log *slog.Logger) (*gin.Engine, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	gormDB, cleanup, err := db.ProvideDB(configConfig, log)
	if err != nil {
		return nil, nil, err
	}
	conversationService := service.NewConversationService(gormDB)
	conversationHandler := handler.NewConversationHandler(conversationService)
	messageService := service.NewMessageService(gormDB)
	hubRegistry := agent.NewHubRegistry(log)
	securityHook := hook.ProvideSecurityHook()
	auditHook := hook.NewAuditHook(log)
	chain := hook.ProvideHookChain(securityHook, auditHook)
	router, cleanup2, err := mcp.ProvideMCPRouter(ctx, configConfig, log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	agentService := agent.ProvideAgentService(gormDB, configConfig, hubRegistry, chain, router, log)
	messageHandler := handler.NewMessageHandler(messageService, agentService, hubRegistry)
	streamHandler := handler.NewStreamHandler(hubRegistry, messageService)
	reportService, err := service.ProvideReportService(ctx, gormDB, conversationService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	reportHandler := handler.NewReportHandler(reportService, messageService, agentService, hubRegistry)
	skillService, err := service.ProvideSkillService(ctx, gormDB)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	skillHandler := handler.NewSkillHandler(skillService)
	serviceAgentService, err := service.ProvideAgentService(ctx, gormDB)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	agentHandler := handler.NewAgentHandler(serviceAgentService)
	engine := handler.ProvideRouter(conversationHandler, messageHandler, streamHandler, reportHandler, skillHandler, agentHandler, log)
	return engine, func() {
		cleanup2()
		cleanup()
	}, nil
}
